package com.oracle.xmlns.carassistanceaznu.mediator.mediatorcomponent;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://soabpm-vm:7001//soa-infra/services/default/Mediator/MediatorComponent_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/CarAssistanceAznu/Mediator/MediatorComponent",
  name="MediatorComponent_ep")
public class MediatorComponent_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.oracle.xmlns.carassistanceaznu.mediator.mediatorcomponent.MediatorComponent_ep");
      URL baseUrl = MediatorComponent_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            MediatorComponent_ep.class.getResource("http://soabpm-vm:7001//soa-infra/services/default/Mediator/MediatorComponent_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://soabpm-vm:7001//soa-infra/services/default/Mediator/MediatorComponent_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://soabpm-vm:7001//soa-infra/services/default/Mediator/MediatorComponent_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://soabpm-vm:7001//soa-infra/services/default/Mediator/MediatorComponent_ep?WSDL",
          e);
    }
  }

  public MediatorComponent_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/CarAssistanceAznu/Mediator/MediatorComponent",
                    "MediatorComponent_ep"));
  }

  public MediatorComponent_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="execute_pt")
  public com.oracle.xmlns.carassistanceaznu.mediator.mediatorcomponent.Execute_ptt getExecute_pt()
  {
    return (com.oracle.xmlns.carassistanceaznu.mediator.mediatorcomponent.Execute_ptt) super.getPort(new QName("http://xmlns.oracle.com/CarAssistanceAznu/Mediator/MediatorComponent",
                                                                                                               "execute_pt"),
                                                                                                     com.oracle.xmlns.carassistanceaznu.mediator.mediatorcomponent.Execute_ptt.class);
  }

  @WebEndpoint(name="execute_pt")
  public com.oracle.xmlns.carassistanceaznu.mediator.mediatorcomponent.Execute_ptt getExecute_pt(WebServiceFeature... features)
  {
    return (com.oracle.xmlns.carassistanceaznu.mediator.mediatorcomponent.Execute_ptt) super.getPort(new QName("http://xmlns.oracle.com/CarAssistanceAznu/Mediator/MediatorComponent",
                                                                                                               "execute_pt"),
                                                                                                     com.oracle.xmlns.carassistanceaznu.mediator.mediatorcomponent.Execute_ptt.class,
                                                                                                     features);
  }
}
