<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="urn:WSDLCarriage"
     xmlns:ns1="urn:WSDLCarriage"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="CarriagePort_PL">
        <plnk:role name="CarriagePort_Role">
            <plnk:portType name="ns1:CarriagePort"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="urn:WSDLCarriage" location="http://soabpm-vm.site:7001/CarAssistanceAznu-Carriage-context-root/CarriagePort?wsdl"/>
</wsdl:definitions>
