package wsdlentitlement;

import javax.xml.ws.WebFault;

@WebFault(faultBean="org.example.assistance.Fault", targetNamespace="http://www.example.org/assistance",
  name="Fault")
public class EntitlementErrorMessage
  extends Exception
{
  private org.example.assistance.Fault faultInfo;

  public EntitlementErrorMessage(String message,
                                 org.example.assistance.Fault faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public EntitlementErrorMessage(String message,
                                 org.example.assistance.Fault faultInfo,
                                 Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public org.example.assistance.Fault getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(org.example.assistance.Fault faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)
